services:
  jenkins:
    privileged: true
    user: root
    container_name: jenkins
    image: jenkins/jenkins:2.454-jdk17
    restart: always
    ports:
      - '80:8080'
      - '50000:50000'
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: