---
# tasks file for odoo_role

- name: "generate docker compose file"
  template:
    src: "docker-compose-odoo.yml.j2"
    dest: "/home/{{ ansible_user }}/docker-compose-odoo.yml"
    mode: '0655'

- name: "start docker compose"
  command: "docker compose -f /home/{{ ansible_user }}/docker-compose-odoo.yml up -d"
