---
# tasks file for odoo_role

- name: Check if target directory exists
  stat:
    path: "{{ target_dir }}"
  register: dir_check

- name: Set working directory
  set_fact:
    working_dir: "{{ target_dir if dir_check.stat.exists else fallback_dir }}"

- name: Display working directory
  debug:
    msg: "Le répertoire de travail est : {{ working_dir }}"

- name: Check if FUSE module is available
  command: find /lib/modules/$(uname -r) -name 'fuse.ko*'
  register: fuse_module_check
  changed_when: false
  ignore_errors: yes

- name: Install FUSE kernel module (Debian/Ubuntu)
  become: yes
  apt:
    name: 
      - linux-modules-extra-{{ ansible_kernel }}
    state: present
  when: fuse_module_check.stdout == "" and ansible_os_family in ["Debian", "Ubuntu"]

- name: Install FUSE kernel module (RedHat/CentOS)
  become: yes
  yum:
    name: 
      - fuse
      - fuse-libs
    state: present
  when: fuse_module_check.stdout == "" and ansible_os_family in ["RedHat", "CentOS"]

- name: Load FUSE module
  become: yes
  command: modprobe fuse
  register: fuse_load
  ignore_errors: yes

- name: Confirm FUSE module loaded
  command: lsmod
  register: lsmod_output
  changed_when: false

- name: Check if FUSE is in the loaded modules
  set_fact:
    fuse_loaded: "{{ 'fuse' in lsmod_output.stdout }}"

- name: Display FUSE module status
  debug:
    msg: "FUSE module loaded: {{ fuse_loaded }}"

- name: Fail if FUSE module not loaded
  fail:
    msg: "FUSE module could not be loaded. Please check kernel configuration. Last dmesg logs: {{ lookup('pipe', 'dmesg | tail -n 10') }}"
  when: not fuse_loaded

- name: Check SELinux status
  command: getenforce
  register: selinux_status
  changed_when: false

- name: Set SELinux to permissive mode if enforcing
  become: yes
  command: setenforce 0
  when: selinux_status.stdout == "Enforcing"

- name: Check if fuse-overlayfs is installed
  command: which fuse-overlayfs
  register: fuse_overlayfs_check
  ignore_errors: yes
  changed_when: false

- name: Check fuse-overlayfs version
  command: fuse-overlayfs --version
  register: fuse_overlayfs_version
  ignore_errors: yes
  changed_when: false

- name: Install or update fuse-overlayfs (Debian/Ubuntu)
  become: yes
  apt:
    name: fuse-overlayfs
    state: latest
  when: fuse_overlayfs_check.rc != 0 and ansible_os_family in ["Debian", "Ubuntu"]

- name: Install or update fuse-overlayfs (RedHat/CentOS)
  become: yes
  yum:
    name: fuse-overlayfs
    state: latest
  when: fuse_overlayfs_check.rc != 0 and ansible_os_family in ["RedHat", "CentOS"]

- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false

- name: Extract Docker version number
  set_fact:
    docker_version_number: "{{ docker_version.stdout | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)') | first }}"

- name: Configure Docker to use overlay2 storage driver
  become: yes
  copy:
    content: |
      {
        "storage-driver": "overlay2",
        "storage-opts": ["overlay2.override_kernel_check=true"],
        "features": {"buildkit": true},
        "experimental": false
      }
    dest: /etc/docker/daemon.json
  notify: Restart Docker service

- name: Ensure Docker socket permissions are correct
  become: yes
  file:
    path: /var/run/docker.sock
    mode: '0666'
  notify: Restart Docker service

- name: Disable SELinux temporarily
  become: yes
  command: setenforce 0
  when: ansible_selinux.status is defined and ansible_selinux.status == 'enabled'
  ignore_errors: yes

- name: Check working directory permissions
  file:
    path: "{{ working_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Ensure Docker service is started and enabled
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker is running
  command: docker info
  register: docker_info
  changed_when: false
  failed_when: docker_info.rc != 0

- name: Generate docker compose file
  template:
    src: "docker-compose-odoo.yml.j2"
    dest: "{{ working_dir }}/docker-compose-odoo.yml"
    mode: '0644'
  when: docker_info.rc == 0

- name: Start docker compose
  command: "docker compose -f {{ working_dir }}/docker-compose-odoo.yml up -d"
  become: yes
  register: docker_compose_result
  when: docker_info.rc == 0

- name: Display Docker Compose output
  debug:
    var: docker_compose_result
  when: docker_compose_result is defined

- name: Display Docker logs
  command: "docker compose -f {{ working_dir }}/docker-compose-odoo.yml logs"
  register: docker_logs
  when: docker_compose_result is defined and docker_compose_result.rc == 0

- name: Show Docker logs
  debug:
    var: docker_logs.stdout_lines
  when: docker_logs is defined

- name: Warn if fallback directory was used
  debug:
    msg: "Attention : Le répertoire de repli ({{ fallback_dir }}) a été utilisé car {{ target_dir }} n'existe pas."
  when: working_dir == fallback_dir
